version: "3.8"
services:

  app:
    tty: true
    build:
      context: .
      target: build
    ports:
      - "3000:3000"
    volumes:
      - ./:/src:cached
      - db_data:/data/
      - go_modules:/go/pkg/mod/
    environment:
      - APP_BASE_URL=http://localhost:3000
      - BIND_ADDRESS=0.0.0.0:3000
      - MASTODON_URL=https://3615.computer/
      - ORG_NAME=3615.computer
    env_file:
      - .env
    command: ash -c "go install github.com/cosmtrek/air@latest && air"

  assets:
    tty: true
    build:
      context: .
      target: build-assets
    volumes:
      - ./:/usr/src/app:cached
      - /usr/src/app/node_modules
    command: npm run build:css

volumes:
  db_data:
  node_modules:
  go_modules:
